CREATE TABLE IF NOT EXISTS zonePublish
(
	zonePublishID	INT UNSIGNED NOT NULL AUTO_INCREMENT,
	acctID		INT UNSIGNED NOT NULL,
	zoneType		TINYINT UNSIGNED,
	zoneData 		BLOB,
	PRIMARY KEY (zonePublishID),
	FOREIGN KEY (acctID)  REFERENCES account(acctID)
)	ENGINE=ndbcluster AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
