package com.inthinc.pro.automation.device_emulation.waysmart.enums;

import java.util.EnumSet;
import java.util.HashMap;


public enum Ways_SAT_EVENT {

	/* Note Types */

	 SAT_EVENT_FULLEVENT(1),
	 SAT_EVENT_NOTEEVENT(2),
	 SAT_EVENT_SEATBELT(3),
	 SAT_EVENT_SPEEDING(4),
	 SAT_EVENT_THEFT(5),
	 SAT_EVENT_LOCATION(6),
	 SAT_EVENT_NEWDRIVER(7),
	 SAT_EVENT_MANDOWN(8),
	 SAT_EVENT_PANIC(9),
	 
	 SAT_EVENT_HOME(11),
	 SAT_EVENT_CHECKUNIT(12),
	 SAT_EVENT_GEOFENCE(13),
	 SAT_EVENT_RPM(14),
	 SAT_EVENT_MAN_OK(15),
	 SAT_EVENT_TEMPERATURE(18),
	 SAT_EVENT_IGNITION_ON(19),
	 
	 SAT_EVENT_IGNITION_OFF(20),
	 SAT_EVENT_MODEM_OFF(21),
	 SAT_EVENT_LOW_BATTERY(22),
	 SAT_EVENT_ACCELERATION(23),
	 SAT_EVENT_DECELERATION(24),
	 SAT_EVENT_WATCHDOG(25),
	 SAT_EVENT_REBOOT(26),
	 SAT_EVENT_VERSION(27),
	 SAT_EVENT_GPS_STATE(28),
	 SAT_EVENT_DATA(29),
	 
	 SAT_EVENT_EVENTDATA(30),
	 SAT_EVENT_CONF(31),
	 SAT_EVENT_ACKNOWLEDGE(33),
	 SAT_EVENT_TRACE(34),
	 SAT_EVENT_INSTALL(35),
	 SAT_EVENT_BASE_VERSION(36),
	 SAT_EVENT_MISSING_PARTS(37),
	 SAT_EVENT_HEADLIGHT(38),
	 SAT_EVENT_BOUNDARY_CHANGE(39),
	 
	 SAT_EVENT_DRIVERSTATE_CHANGE(40),
	 SAT_EVENT_ENDOFMONTH(41),
	 SAT_EVENT_TIMESTAMP(42),
	 SAT_EVENT_HOS_RECEIVED(43),
	 SAT_EVENT_LOCATIONDEBUG(44),
	 SAT_EVENT_CRASH_DATA(45),
	 SAT_EVENT_NO_DRIVER(46),
	 SAT_EVENT_ON_ROAD(47),
	 SAT_EVENT_OFF_ROAD(48),
	 SAT_EVENT_SPEEDING_EX(49),
	 
	 SAT_EVENT_ERROR(50),
	 SAT_EVENT_STATS(51),
	 SAT_EVENT_LOW_POWER_MODE(52),
	 SAT_EVENT_SATELLITE_SWITCH(53),
	 SAT_EVENT_WITNESS_HEARTBEAT_VIOLATION(54),
	 SAT_EVENT_DRIVER_HOURS(55),
	 SAT_EVENT_DOT_STOPPED(56),
	 SAT_EVENT_ODOMETER(57),
	 SAT_EVENT_SPEEDING_EX2(58),
	 SAT_EVENT_NO_TRAILER(59),
	 
	 SAT_EVENT_24HR_REBOOT(60),
	 SAT_EVENT_FIRMWARE_REBOOT(61),
	 SAT_EVENT_KEYPAD_REBOOT(62),
	 SAT_EVENT_CMD_REBOOT(63),
	 SAT_EVENT_TRAILER_DATA(64),
	 SAT_EVENT_KEYPAD(65),
	 SAT_EVENT_CLEAR_DRIVER(66),
	 SAT_EVENT_HOS_NO_HOURS(67),
	 SAT_EVENT_HOS_LOG_RECORD(68),
	 SAT_EVENT_HOS_SUMMARY_RECEIVED(69),
	 
	 SAT_EVENT_HOS_SUMMARY_RECORD(70),
	 SAT_EVENT_WAYPOINT(71),
	 SAT_EVENT_TEXT_MSG(72),
	 SAT_EVENT_FUEL_STOP(73),
	 SAT_EVENT_FIRMWARE_UP_TO_DATE(74),
	 SAT_EVENT_MAPS_UP_TO_DATE(75),
	 SAT_EVENT_ZONES_UP_TO_DATE(76),
	 SAT_EVENT_BOOT_LOADER_UP_TO_DATE(77),
	 SAT_EVENT_WSZONES_ARRIVAL(78),
	 
	 SAT_EVENT_TEXT_MSG_CANNED(80),
	 SAT_EVENT_QUEUE_FULL(81),
	 SAT_EVENT_GPIO_SHUT_DOWN(82),
	 SAT_EVENT_WAYPOINT_EX(83),
	 SAT_EVENT_MANDOWN_PENDING(84),
	 SAT_EVENT_PRE_TRIP_INSPECTION(85),
	 SAT_EVENT_POST_TRIP_INSPECTION(86),
	 SAT_EVENT_WSZONES_DEPARTURE(87),
	 SAT_EVENT_HOS_30_MIN(88),
	 SAT_EVENT_HOS_MINUS_15(89),
	 
	 SAT_EVENT_HOS_MINUS_30(90),
	 SAT_EVENT_XCAT(91),
	 SAT_EVENT_DMR(92),
	 SAT_EVENT_SPEEDING_EX3(93),
	 SAT_EVENT_COLILO_VERSION(94),
	 SAT_EVENT_TRIAX_STATUS(95),
	 SAT_EVENT_DRIVERSTATE_CHANGE_EX(96),
	 SAT_EVENT_LIGHT_DUTY(97),
	 SAT_EVENT_HEAVY_DUTY(98),
	 SAT_EVENT_MISSING_IWI_CONF(99),
	 SAT_EVENT_INVALID_OCCUPANT(104),
	 
	 SAT_EVENT_TRIAX_STATUS_EX(110),
	 SAT_EVENT_CRASH_DATA_EXTENDED(112),
	 SAT_EVENT_HOS_CHANGE_STATE_NO_GPS_LOCK(113),
	 SAT_EVENT_NEWDRIVER_HOSRULE(116),
	 SAT_EVENT_WSZONES_ARRIVAL_EX(117),
	 SAT_EVENT_WSZONES_DEPARTURE_EX(118),
	 SAT_EVENT_REQUEST_SPECIFIC_DETAIL_RECORDS(119),
	 
	 SAT_EVENT_WITNESSII_STATUS(120),
	 SAT_EVENT_WITNESSII_LIST(121),
	 SAT_EVENT_QSI_UP_TO_DATE(122),
	 SAT_EVENT_WITNESS_UP_TO_DATE(123),
	 SAT_EVENT_TRIAX_UP_TO_DATE(124),
	 SAT_EVENT_TRIAX_STATUS_DIAGNOSTIC(125),
	 SAT_EVENT_IWICONF_LOAD_ERROR(126),
	 SAT_EVENT_INSTALLATION_CHECKLIST(127),
	 SAT_EVENT_WITNESSII_CHANGE_CONFIG_ACK(128),
	 SAT_EVENT_GET_WITNESSII_STATUS(129),
	 
	 SAT_EVENT_WITNESSII_TRACE(130),
	 SAT_EVENT_WITNESSII_TRACE_OVERWRITTEN(131),
	 SAT_EVENT_WITNESSII_ARCHIVE_HEADER(132),
	 SAT_EVENT_CLEAR_OCCUPANT(133),
	 SAT_EVENT_WITNESSII_ARCHIVED_TRACE_UPLOADED(134),
	 SAT_EVENT_ACKNOWLEDGE_UPDATE(135),
	 SAT_EVENT_BOUNDARYDAT_UP_TO_DATE(136),
	 SAT_EVENT_PLACES2DAT_UP_TO_DATE(137),
	 
	 SAT_EVENT_IDLE_STATS(140),
	 WITNESSII_EVENT_DIAGNOSTIC(141),
	 SAT_EVENT_AUTOMANDOWN(142),
	 SAT_EVENT_AUTO_MAN_OK(143),
	 SAT_EVENT_SMTOOLS_EMULATION_UP_TO_DATE(144),
	 SAT_EVENT_SMTOOLS_FIRMWARE_UP_TO_DATE(145),
	 SAT_EVENT_SMTOOLS_SECURITY_DISABLE(146),
	 SAT_EVENT_TRIAX_STATUS_WITNESSIII(147),
	 SAT_EVENT_SMTOOLS_DEVICE_STATUS(148),
	 SAT_EVENT_OBD_PARAMS_STATUS(149),

	 SAT_EVENT_POWER_ON(150),
	 SAT_EVENT_INTRASTATE_VIOLATION(151),
	 SAT_EVENT_POTENTIAL_CRASH(152),
	 SAT_EVENT_CANCEL_POTENTIAL_CRASH(153),
	 SAT_EVENT_USB_REBOOT(154),
	 SAT_EVENT_SMTOOLS_DEVICE_STATUS_EX(155),
	 SAT_EVENT_OBD_PARAMS_STATUS_EX(156),
	 SAT_EVENT_CHECK_HOSMINUTES(157),
	 SAT_EVENT_WIRELINE_STATUS (158), //sent after every forward command received
	 SAT_EVENT_WIRELINE_ALARM (159), //sent when door alarm siren triggered
	 
	 SAT_EVENT_WIRELINE_IGN_TEST_NOT_RUN(160),
	 SAT_EVENT_WIRELINE_IGN_TEST_FAIL(161),
	 SAT_EVENT_WIRELINE_IGN_TEST_PASS(162),
	 SAT_EVENT_SHELL_OUTPUT(163),
	 SAT_EVENT_NO_MAPS_DRIVE(164),
	 SAT_EVENT_AUTODETECT(165),
	 SAT_EVENT_FUEL_STOP_EX(166),
	 LOWPOWER_TAMPER_EVENT(167),
	 SAT_EVENT_FULLEVENT_BELOW_THRESHOLD(168),
	 SAT_EVENT_ROLLOVER(169),
	 
	 SAT_EVENT_TRIAX_STATUS_WITNESSIII_TEMPCOMP(170),
	 SAT_EVENT_VERTICALEVENT(171), 
	 SAT_EVENT_PARKINGBRAKE(172), 
	 SAT_EVENT_UNIT_INFO(173), 
	 SAT_EVENT_FULLEVENT_CONFIDENCE_LEVEL(174), 
	 SAT_EVENT_CRASH_DATA_HIRES(175),
	 SAT_EVENT_DSS_MICROSLEEP(176), 
	 SAT_EVENT_DSS_STATISTICS(177), 
	 SAT_EVENT_NOTEEVENT_SECONDARY(178),
	 SAT_EVENT_VERTICALEVENT_SECONDARY(179),
	 
	 SAT_EVENT_WEEKLY_GPRS_USAGE(180),	
	 SAT_EVENT_MCM_APP_FIRMWARE_UP_TO_DATE(181),	
	 SAT_EVENT_REMOTE_AUTO_MANDOWN(182),   // automatic -no motion 	mandown
	 SAT_EVENT_REMOTE_MAN_MANDOWN(183),  // manual mandown
	 SAT_EVENT_REMOTE_OK_MANDOWN(184),  // mandown cancelled
	 SAT_EVENT_REMOTE_OFF_MANDOWN(185),  // remote turned off
	 SAT_EVENT_REMOTE_LOW_BATT_MANDOWN(186),  // low battery on remote
	 SAT_EVENT_REMOTE_ON_MANDONW(187),  // remote turned on
	 SAT_EVENT_REMOTE_AACK_MANDOWN(188),
	 SAT_EVENT_SBS_UPDATE(189),  // remote turned on
	 
	 SAT_EVENT_EMU_TARBALL_UP_TO_DATE(190),
	 SAT_EVENT_SPEEDING_EX4(191),
	 SAT_EVENT_SPEEDING_LOG4(192),
	 SAT_EVENT_BLAST_ZONE_RECEIVED(193),
	 SAT_EVENT_SPEEDING_AV(194),
	 SAT_EVENT_UNIT_TEST_INFORMATION(195),
	 SAT_EVENT_UNIT_TEST_WARNING(196),
	 SAT_EVENT_UNIT_TEST_CRITICAL(197),
	 
	 IDLE(208),

	 SAT_EVENT_IDLE_FAKETIME(214),

	// new notifications without header information - not really a real notification.
	// used primarily for background communication
	 SAT_EVENT_STRIPPED_LOWER_LIMIT(243),
	 SAT_EVENT_STRIPPED_UPPER_LIMIT(255),
	 SAT_EVENT_STRIPPED_ACKNOWLEDGE_ID_WITH_DATA(246),
	 WIFI_EVENT_STRIPPED_GET_WITNESSII_EVENT_TRACE(248),
	 SAT_EVENT_STRIPPED_GET_WITNESSII_EVENT_LIST_EX(249),
	 
	 SAT_EVENT_STRIPPED_GET_SPECIFIC_DETAIL_RECORDS(250),
	 SAT_EVENT_STRIPPED_GET_SHORT_ID(251),
	 SAT_EVENT_GET_OCCUPANTS_STRIPPED(252),
	 SAT_EVENT_GET_OCCUPANT_INFO_STRIPPED(253),
	 SAT_EVENT_ACKNOWLEDGE_STRIPPED(254),	 
		
	 SAT_EVENT_MAX_ID(300);

	 
	 private int code;

	 private Ways_SAT_EVENT(int c) {
	   code = c;
	 }

	 public int getCode() {
	   return code;
	 }
	 
	 private static HashMap<Integer, Ways_SAT_EVENT> lookupByCode = new HashMap<Integer, Ways_SAT_EVENT>();
	    
	    static {
	        for (Ways_SAT_EVENT p : EnumSet.allOf(Ways_SAT_EVENT.class))
	        {
	            lookupByCode.put(p.getCode(), p);
	        }
	    }
	    
	    public static Ways_SAT_EVENT valueOf(Integer code){
	    	return lookupByCode.get(code);
	    }
}
