package com.inthinc.pro.reports.hos;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.TimeZone;

import org.junit.Test;

import com.inthinc.hos.model.HOSOrigin;
import com.inthinc.hos.model.HOSRecAdjusted;
import com.inthinc.hos.model.HOSStatus;
import com.inthinc.hos.model.RuleSetType;
import com.inthinc.pro.model.hos.HOSRecord;
import com.inthinc.pro.reports.BaseUnitTest;
import com.inthinc.pro.reports.FormatType;
import com.inthinc.pro.reports.ReportCriteria;
import com.inthinc.pro.reports.hos.model.HosDailyDriverLog;
import com.inthinc.pro.reports.hos.model.Recap;
import com.inthinc.pro.reports.hos.model.RecapCanada;
import com.inthinc.pro.reports.hos.model.RecapCanada2007;
import com.inthinc.pro.reports.hos.model.RecapType;
import com.inthinc.pro.reports.hos.model.RecapUS;
import com.inthinc.pro.reports.hos.model.RemarkLog;
import com.inthinc.pro.reports.hos.testData.DDLDataSet;

public class HosDriverDailyLogReportCriteriaTest extends BaseUnitTest{

    // these csv files were generated by connecting to the gain db and running the stored proc 
    //   hos_fetchLogsForDriver driverID, startDate, endDate 
    // for example:
    //   hos_fetchLogsForDriver '945463F0-44A8-4B85-9BA3-2EDAD2A9B501', '03/08/2010', '03/31/2010'
    // start date should be 20 days prior to the date you want to run the ddl report for
    // the results should be exported to csv and named test#_ddlStartDate_ddlEndDate_rule<type>
    // the csv file should be copied to test/resources/ddl and added to the list below
    // to compare run the same report for the same driver/date range in gain and copy the resulting pdf
    // to test/resources/ddl/test#Expected.pdf  -- recap, graphs, and remarks should be the same
    public static final String testCaseName[] = {
        "test0_03302010_04012010_rule2",
        "test1_01242010_01312010_rule2",
        "test2_03012010_03052010_rule2",
        "test3_06202010_06302010_rule13",
        "test4_06202010_06302010_rule7",
        "test5_06202010_06302010_rule1",
        "test6_04182010_04202010_rule10",
        "test7_06202010_06302010_rule14",
        "test8_06202010_06302010_rule6",
        "test9_06202010_06302010_rule8",
        "test10_06052010_06152010_rule9",
        "test11_01192010_01212010_rule11",
        "test12_07132010_07172010_personalTime",
        "test13_06062010_06102010_travelTimeOccupant",
        "test14_01242010_01312010_rule16",
    };

    public static final int testDay[] = {
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0
    };
    public HOSRecAdjusted expectedAdjustedList[][]  = {
              {     // test0_03302010_04012010_rule2
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1269928800000l),TimeZone.getTimeZone("UTC"),new Date(1269928800000l),480l,0,32,false,"","",480l,RuleSetType.US_OIL, 1),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1269957600000l),TimeZone.getTimeZone("UTC"),new Date(1269957600000l),15l,32,1,false,"","",8l,RuleSetType.US_OIL, null),
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1269957600000l),TimeZone.getTimeZone("UTC"),new Date(1269957600000l),0l,33,0,false,"","",7l,RuleSetType.US_OIL, null),
                new HOSRecAdjusted("1",HOSStatus.OFF_DUTY,new Date(1269958500000l),TimeZone.getTimeZone("UTC"),new Date(1269958500000l),90l,33,6,false,"","",90l,RuleSetType.US_OIL, 1),
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1269963900000l),TimeZone.getTimeZone("UTC"),new Date(1269963900000l),0l,39,0,false,"","",7l,RuleSetType.US_OIL, null),
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1269963900000l),TimeZone.getTimeZone("UTC"),new Date(1269963900000l),15l,39,1,false,"","",8l,RuleSetType.US_OIL, null),
                new HOSRecAdjusted("0",HOSStatus.OFF_DUTY,new Date(1269964800000l),TimeZone.getTimeZone("UTC"),new Date(1269964800000l),3720l,40,56,false,"","",3720l,RuleSetType.US_OIL, 1),
                
            },
        {   // test1_01242010_01312010_rule2
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1264316400000l),TimeZone.getTimeZone("UTC"),new Date(1264316400000l),1440l,0,96,false,"","",1440l,RuleSetType.US_OIL, 17),
        },
        {   // test2_03012010_03052010_rule2
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1267426800000l),TimeZone.getTimeZone("UTC"),new Date(1267426800000l),1440l,0,96,false,"","",1440l,RuleSetType.US_OIL, 2),
        },
        {   // test3_06202010_06302010_rule13
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1277103600000l),TimeZone.getTimeZone("UTC"),new Date(1277103600000l),345l,0,23,false,"","",345l,RuleSetType.CANADA_2007_OIL, 1),
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1277124300000l),TimeZone.getTimeZone("UTC"),new Date(1277124300000l),15l,23,1,false,"","",12l,RuleSetType.CANADA_2007_OIL, 1),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1277124300000l),TimeZone.getTimeZone("UTC"),new Date(1277124300000l),0l,24,0,false,"","",3l,RuleSetType.CANADA_2007_OIL, 1),
                new HOSRecAdjusted("19",HOSStatus.ON_DUTY,new Date(1277125200000l),TimeZone.getTimeZone("UTC"),new Date(1277125200000l),0l,24,0,false,"","",14l,RuleSetType.CANADA_2007_OIL, 1),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1277125200000l),TimeZone.getTimeZone("UTC"),new Date(1277125200000l),15l,24,1,false,"380039","",0l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("17",HOSStatus.ON_DUTY,new Date(1277126100000l),TimeZone.getTimeZone("UTC"),new Date(1277126100000l),0l,25,0,false,"380039","",0l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1277126100000l),TimeZone.getTimeZone("UTC"),new Date(1277126100000l),15l,25,1,false,"380039","",12l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1277126100000l),TimeZone.getTimeZone("UTC"),new Date(1277126100000l),0l,26,0,false,"380039","",2l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("16",HOSStatus.DRIVING,new Date(1277127000000l),TimeZone.getTimeZone("UTC"),new Date(1277127000000l),0l,26,0,false,"380039","",0l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1277127000000l),TimeZone.getTimeZone("UTC"),new Date(1277127000000l),0l,26,0,false,"380039","",4l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1277127000000l),TimeZone.getTimeZone("UTC"),new Date(1277127000000l),15l,26,1,false,"380039","",10l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("15",HOSStatus.ON_DUTY,new Date(1277127900000l),TimeZone.getTimeZone("UTC"),new Date(1277127900000l),15l,27,1,false,"380039","",15l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1277128800000l),TimeZone.getTimeZone("UTC"),new Date(1277128800000l),15l,28,1,false,"380039","",8l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1277128800000l),TimeZone.getTimeZone("UTC"),new Date(1277128800000l),0l,29,0,false,"380039","",6l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("14",HOSStatus.DRIVING,new Date(1277129700000l),TimeZone.getTimeZone("UTC"),new Date(1277129700000l),45l,29,3,false,"380039","",45l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1277132400000l),TimeZone.getTimeZone("UTC"),new Date(1277132400000l),0l,32,0,false,"380039","",5l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1277132400000l),TimeZone.getTimeZone("UTC"),new Date(1277132400000l),15l,32,1,false,"380039","",9l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("12",HOSStatus.ON_DUTY,new Date(1277133300000l),TimeZone.getTimeZone("UTC"),new Date(1277133300000l),315l,33,21,false,"380039","",315l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1277152200000l),TimeZone.getTimeZone("UTC"),new Date(1277152200000l),15l,54,1,false,"380039","",12l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1277152200000l),TimeZone.getTimeZone("UTC"),new Date(1277152200000l),0l,55,0,false,"380039","",2l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("11",HOSStatus.DRIVING,new Date(1277153100000l),TimeZone.getTimeZone("UTC"),new Date(1277153100000l),45l,55,3,false,"380039","",45l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1277155800000l),TimeZone.getTimeZone("UTC"),new Date(1277155800000l),0l,58,0,false,"380039","",9l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("9",HOSStatus.ON_DUTY,new Date(1277155800000l),TimeZone.getTimeZone("UTC"),new Date(1277155800000l),0l,58,0,false,"380039","",0l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1277155800000l),TimeZone.getTimeZone("UTC"),new Date(1277155800000l),15l,58,1,false,"380039","",5l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("8",HOSStatus.DRIVING,new Date(1277156700000l),TimeZone.getTimeZone("UTC"),new Date(1277156700000l),0l,59,0,false,"380039","",0l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1277156700000l),TimeZone.getTimeZone("UTC"),new Date(1277156700000l),0l,59,0,false,"380039","",6l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("7",HOSStatus.ON_DUTY,new Date(1277156700000l),TimeZone.getTimeZone("UTC"),new Date(1277156700000l),15l,59,1,false,"380039","",8l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("6",HOSStatus.DRIVING,new Date(1277156700000l),TimeZone.getTimeZone("UTC"),new Date(1277156700000l),0l,60,0,false,"380039","",1l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("4",HOSStatus.ON_DUTY,new Date(1277157600000l),TimeZone.getTimeZone("UTC"),new Date(1277157600000l),15l,60,1,false,"380039","",14l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1277158500000l),TimeZone.getTimeZone("UTC"),new Date(1277158500000l),15l,61,1,false,"380039","",15l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1277159400000l),TimeZone.getTimeZone("UTC"),new Date(1277159400000l),0l,62,0,false,"380039","",7l,RuleSetType.CANADA_2007_OIL, 2),
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1277159400000l),TimeZone.getTimeZone("UTC"),new Date(1277159400000l),15l,62,1,false,"","",8l,RuleSetType.CANADA_2007_OIL, 1),
                new HOSRecAdjusted("3",HOSStatus.OFF_DUTY,new Date(1277160300000l),TimeZone.getTimeZone("UTC"),new Date(1277160300000l),12540l,63,33,false,"","",12540l,RuleSetType.CANADA_2007_OIL, 1),
        },
        {   // test4_06202010_06302010_rule7
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1277010000000l),TimeZone.getTimeZone("UTC"),new Date(1277010000000l),1440l,0,96,false,"","",1440l,RuleSetType.TEXAS, 32),
        },
        {   // test5_06202010_06302010_rule1
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1277010000000l),TimeZone.getTimeZone("UTC"),new Date(1277010000000l),1440l,0,96,false,"","",1440l,RuleSetType.US, 10),
        },
        {   // test6_04182010_04202010_rule10
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1271570400000l),TimeZone.getTimeZone("UTC"),new Date(1271570400000l),1440l,0,96,false,"","",1440l,RuleSetType.NON_DOT, 6),
        },
        {   // test7_06202010_06302010_rule14
            new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1277013600000l),TimeZone.getTimeZone("UTC"),new Date(1277013600000l),645l,0,43,false,"","",645l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1277052300000l),TimeZone.getTimeZone("UTC"),new Date(1277052300000l),15l,43,1,false,"","",11l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("46",HOSStatus.ON_DUTY,new Date(1277052300000l),TimeZone.getTimeZone("UTC"),new Date(1277052300000l),0l,44,0,false,"","",0l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1277052300000l),TimeZone.getTimeZone("UTC"),new Date(1277052300000l),0l,44,0,false,"","",3l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("45",HOSStatus.DRIVING,new Date(1277053200000l),TimeZone.getTimeZone("UTC"),new Date(1277053200000l),0l,44,0,false,"","",0l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1277053200000l),TimeZone.getTimeZone("UTC"),new Date(1277053200000l),0l,44,0,false,"","",2l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("44",HOSStatus.ON_DUTY,new Date(1277053200000l),TimeZone.getTimeZone("UTC"),new Date(1277053200000l),0l,44,0,false,"","",1l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("42",HOSStatus.DRIVING,new Date(1277053200000l),TimeZone.getTimeZone("UTC"),new Date(1277053200000l),0l,44,0,false,"","",5l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1277053200000l),TimeZone.getTimeZone("UTC"),new Date(1277053200000l),15l,44,1,false,"","",6l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("41",HOSStatus.ON_DUTY,new Date(1277054100000l),TimeZone.getTimeZone("UTC"),new Date(1277054100000l),15l,45,1,false,"","",15l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1277055000000l),TimeZone.getTimeZone("UTC"),new Date(1277055000000l),15l,46,1,false,"","",12l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1277055000000l),TimeZone.getTimeZone("UTC"),new Date(1277055000000l),0l,47,0,false,"","",2l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("40",HOSStatus.DRIVING,new Date(1277055900000l),TimeZone.getTimeZone("UTC"),new Date(1277055900000l),0l,47,0,false,"","",0l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1277055900000l),TimeZone.getTimeZone("UTC"),new Date(1277055900000l),15l,47,1,false,"","",8l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1277055900000l),TimeZone.getTimeZone("UTC"),new Date(1277055900000l),0l,48,0,false,"","",6l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("39",HOSStatus.ON_DUTY,new Date(1277056800000l),TimeZone.getTimeZone("UTC"),new Date(1277056800000l),45l,48,3,false,"","",45l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1277059500000l),TimeZone.getTimeZone("UTC"),new Date(1277059500000l),15l,51,1,false,"","",10l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("38",HOSStatus.DRIVING,new Date(1277059500000l),TimeZone.getTimeZone("UTC"),new Date(1277059500000l),0l,52,0,false,"","",4l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1277059500000l),TimeZone.getTimeZone("UTC"),new Date(1277059500000l),0l,52,0,false,"","",0l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
            new HOSRecAdjusted("37",HOSStatus.OFF_DUTY,new Date(1277060400000l),TimeZone.getTimeZone("UTC"),new Date(1277060400000l),1155l,52,44,false,"","",1155l,RuleSetType.CANADA_2007_60_DEGREES_OIL, 2),
        },
        {   // test8_06202010_06302010_rule6
//                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1277006400000l),TimeZone.getTimeZone("UTC"),new Date(1277006400000l),495l,0,33,false,"","",496l,RuleSetType.CANADA_HOME_OFFICE, 51),
//                new HOSRecAdjusted("50",HOSStatus.ON_DUTY_OCCUPANT,new Date(1277036100000l),TimeZone.getTimeZone("UTC"),new Date(1277036100000l),30l,33,2,false,"0","",21l,RuleSetType.CANADA_HOME_OFFICE, 50),
//                new HOSRecAdjusted("49",HOSStatus.OFF_DUTY,new Date(1277037900000l),TimeZone.getTimeZone("UTC"),new Date(1277037900000l),225l,35,15,false,"","",232l,RuleSetType.CANADA_HOME_OFFICE, 49),
//                new HOSRecAdjusted("48",HOSStatus.ON_DUTY_OCCUPANT,new Date(1277051400000l),TimeZone.getTimeZone("UTC"),new Date(1277051400000l),60l,50,4,false,"","",61l,RuleSetType.CANADA_HOME_OFFICE, 48),
//                new HOSRecAdjusted("47",HOSStatus.OFF_DUTY,new Date(1277055000000l),TimeZone.getTimeZone("UTC"),new Date(1277055000000l),1260l,54,42,false,"","",1254l,RuleSetType.CANADA_HOME_OFFICE, 47),

                
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1277006400000l),TimeZone.getTimeZone("UTC"),new Date(1277006400000l),495l,0,33,false,"","",495l,RuleSetType.CANADA_HOME_OFFICE, 3),
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1277036100000l),TimeZone.getTimeZone("UTC"),new Date(1277036100000l),0l,33,0,false,"","",1l,RuleSetType.CANADA_HOME_OFFICE, 3),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY_OCCUPANT,new Date(1277036100000l),TimeZone.getTimeZone("UTC"),new Date(1277036100000l),15l,33,1,false,"0","",13l,RuleSetType.CANADA_HOME_OFFICE, 3),
                new HOSRecAdjusted("50",HOSStatus.ON_DUTY_OCCUPANT,new Date(1277037000000l),TimeZone.getTimeZone("UTC"),new Date(1277037000000l),0l,34,0,false,"0","",0l,RuleSetType.CANADA_HOME_OFFICE, 3),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY_OCCUPANT,new Date(1277037000000l),TimeZone.getTimeZone("UTC"),new Date(1277037000000l),15l,34,1,false,"0","",8l,RuleSetType.CANADA_HOME_OFFICE, 3),
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1277037000000l),TimeZone.getTimeZone("UTC"),new Date(1277037000000l),0l,35,0,false,"","",6l,RuleSetType.CANADA_HOME_OFFICE, 3),
                new HOSRecAdjusted("49",HOSStatus.OFF_DUTY,new Date(1277037900000l),TimeZone.getTimeZone("UTC"),new Date(1277037900000l),225l,35,15,false,"","",225l,RuleSetType.CANADA_HOME_OFFICE, 3),
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1277051400000l),TimeZone.getTimeZone("UTC"),new Date(1277051400000l),0l,50,0,false,"","",1l,RuleSetType.CANADA_HOME_OFFICE, 3),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY_OCCUPANT,new Date(1277051400000l),TimeZone.getTimeZone("UTC"),new Date(1277051400000l),15l,50,1,false,"","",13l,RuleSetType.CANADA_HOME_OFFICE, 3),
                new HOSRecAdjusted("48",HOSStatus.ON_DUTY_OCCUPANT,new Date(1277052300000l),TimeZone.getTimeZone("UTC"),new Date(1277052300000l),45l,51,3,false,"","",45l,RuleSetType.CANADA_HOME_OFFICE, 3),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY_OCCUPANT,new Date(1277055000000l),TimeZone.getTimeZone("UTC"),new Date(1277055000000l),0l,54,0,false,"","",2l,RuleSetType.CANADA_HOME_OFFICE, 3),
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1277055000000l),TimeZone.getTimeZone("UTC"),new Date(1277055000000l),15l,54,1,false,"","",12l,RuleSetType.CANADA_HOME_OFFICE, 3),
                new HOSRecAdjusted("47",HOSStatus.OFF_DUTY,new Date(1277055900000l),TimeZone.getTimeZone("UTC"),new Date(1277055900000l),1230l,55,41,false,"","",1230l,RuleSetType.CANADA_HOME_OFFICE, 3),
                
        },
        {   // test9_06202010_06302010_rule8
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1277013600000l),TimeZone.getTimeZone("UTC"),new Date(1277013600000l),1440l,0,96,false,"","",1440l,RuleSetType.CANADA_ALBERTA, 74),
        },
        {   // test10_06052010_06152010_rule9
            new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1275710400000l),TimeZone.getTimeZone("UTC"),new Date(1275710400000l),540l,0,36,false,"","",540l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1275742800000l),TimeZone.getTimeZone("UTC"),new Date(1275742800000l),0l,36,0,false,"","",1l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("35",HOSStatus.ON_DUTY,new Date(1275742800000l),TimeZone.getTimeZone("UTC"),new Date(1275742800000l),0l,36,0,false,"1","",0l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("34",HOSStatus.DRIVING,new Date(1275742800000l),TimeZone.getTimeZone("UTC"),new Date(1275742800000l),0l,36,0,false,"1","",6l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("33",HOSStatus.ON_DUTY,new Date(1275742800000l),TimeZone.getTimeZone("UTC"),new Date(1275742800000l),0l,36,0,false,"1","",0l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1275742800000l),TimeZone.getTimeZone("UTC"),new Date(1275742800000l),15l,36,1,false,"1","",6l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("32",HOSStatus.DRIVING,new Date(1275743700000l),TimeZone.getTimeZone("UTC"),new Date(1275743700000l),30l,37,2,false,"1","",30l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1275745500000l),TimeZone.getTimeZone("UTC"),new Date(1275745500000l),0l,39,0,false,"1","",3l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1275745500000l),TimeZone.getTimeZone("UTC"),new Date(1275745500000l),15l,39,1,false,"","",11l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("30",HOSStatus.OFF_DUTY,new Date(1275746400000l),TimeZone.getTimeZone("UTC"),new Date(1275746400000l),450l,40,30,false,"","",450l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1275773400000l),TimeZone.getTimeZone("UTC"),new Date(1275773400000l),15l,70,1,false,"","",8l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("28",HOSStatus.ON_DUTY,new Date(1275773400000l),TimeZone.getTimeZone("UTC"),new Date(1275773400000l),0l,71,0,false,"1","",0l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1275773400000l),TimeZone.getTimeZone("UTC"),new Date(1275773400000l),0l,71,0,false,"1","",5l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("27",HOSStatus.DRIVING,new Date(1275774300000l),TimeZone.getTimeZone("UTC"),new Date(1275774300000l),30l,71,2,false,"1","",30l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("generated",HOSStatus.DRIVING,new Date(1275776100000l),TimeZone.getTimeZone("UTC"),new Date(1275776100000l),0l,73,0,false,"1","",5l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1275776100000l),TimeZone.getTimeZone("UTC"),new Date(1275776100000l),15l,73,1,false,"","",9l,RuleSetType.CANADA_2007_CYCLE_1, 1),
            new HOSRecAdjusted("26",HOSStatus.OFF_DUTY,new Date(1275777000000l),TimeZone.getTimeZone("UTC"),new Date(1275777000000l),675l,74,22,false,"","",675l,RuleSetType.CANADA_2007_CYCLE_1, 1),
        },
        {   // test11_01192010_01212010_rule11
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1263873600000l),TimeZone.getTimeZone("UTC"),new Date(1263873600000l),1440l,0,96,false,"","",1440l,RuleSetType.CANADA_2007_60_DEGREES_CYCLE_1, 9),
        },
        {   // test12_07132010_07172010_personalTime
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1279087200000l),TimeZone.getTimeZone("UTC"),new Date(1279087200000l),360l,0,24,false,"","",360l,RuleSetType.CANADA_2007_CYCLE_1, 1),
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1279108800000l),TimeZone.getTimeZone("UTC"),new Date(1279108800000l),0l,24,0,false,"","",5l,RuleSetType.CANADA_2007_CYCLE_1, 1),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY_OCCUPANT,new Date(1279108800000l),TimeZone.getTimeZone("UTC"),new Date(1279108800000l),15l,24,1,false,"","",9l,RuleSetType.CANADA_2007_CYCLE_1, 1),
                new HOSRecAdjusted("14",HOSStatus.ON_DUTY_OCCUPANT,new Date(1279109700000l),TimeZone.getTimeZone("UTC"),new Date(1279109700000l),690l,25,46,false,"","",690l,RuleSetType.CANADA_2007_CYCLE_1, 1),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY_OCCUPANT,new Date(1279151100000l),TimeZone.getTimeZone("UTC"),new Date(1279151100000l),0l,71,0,false,"","",2l,RuleSetType.CANADA_2007_CYCLE_1, 1),
                new HOSRecAdjusted("generated",HOSStatus.HOS_PERSONALTIME,new Date(1279151100000l),TimeZone.getTimeZone("UTC"),new Date(1279151100000l),15l,71,1,false,"","",13l,RuleSetType.CANADA_2007_CYCLE_1, 1),
                new HOSRecAdjusted("10",HOSStatus.HOS_PERSONALTIME,new Date(1279152000000l),TimeZone.getTimeZone("UTC"),new Date(1279152000000l),105l,72,7,false,"","",105l,RuleSetType.CANADA_2007_CYCLE_1, 1),
                new HOSRecAdjusted("generated",HOSStatus.HOS_PERSONALTIME,new Date(1279158300000l),TimeZone.getTimeZone("UTC"),new Date(1279158300000l),0l,79,0,false,"","",12l,RuleSetType.CANADA_2007_CYCLE_1, 1),
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1279158300000l),TimeZone.getTimeZone("UTC"),new Date(1279158300000l),15l,79,1,false,"","",2l,RuleSetType.CANADA_2007_CYCLE_1, 1),
                new HOSRecAdjusted("9",HOSStatus.OFF_DUTY,new Date(1279159200000l),TimeZone.getTimeZone("UTC"),new Date(1279159200000l),660l,80,16,false,"","",660l,RuleSetType.CANADA_2007_CYCLE_1, 1),
        },
        {   // test13_06062010_06102010_travelTimeOccupant
//                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1275804000000l),TimeZone.getTimeZone("UTC"),new Date(1275804000000l),1020l,0,68,true,"","",1021l,RuleSetType.US_OIL, 56),
//                new HOSRecAdjusted("55",HOSStatus.ON_DUTY,new Date(1275865200000l),TimeZone.getTimeZone("UTC"),new Date(1275865200000l),0l,68,0,true,"","",1l,RuleSetType.US_OIL, 55),
//                new HOSRecAdjusted("54",HOSStatus.TRAVELTIME_OCCUPANT,new Date(1275865200000l),TimeZone.getTimeZone("UTC"),new Date(1275865200000l),180l,68,12,true,"","",174l,RuleSetType.US_OIL, 54),
//                new HOSRecAdjusted("53",HOSStatus.OFF_DUTY,new Date(1275876000000l),TimeZone.getTimeZone("UTC"),new Date(1275876000000l),615l,80,16,false,"","",624l,RuleSetType.US_OIL, 53),
                
                
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1275804000000l),TimeZone.getTimeZone("UTC"),new Date(1275804000000l),1020l,0,68,true,"","",1020l,RuleSetType.US_OIL, 1),
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1275865200000l),TimeZone.getTimeZone("UTC"),new Date(1275865200000l),15l,68,1,true,"","",1l,RuleSetType.US_OIL, 1),
                new HOSRecAdjusted("55",HOSStatus.ON_DUTY,new Date(1275865200000l),TimeZone.getTimeZone("UTC"),new Date(1275865200000l),0l,69,0,true,"","",1l,RuleSetType.US_OIL, 1),
                new HOSRecAdjusted("generated",HOSStatus.TRAVELTIME_OCCUPANT,new Date(1275865200000l),TimeZone.getTimeZone("UTC"),new Date(1275865200000l),0l,69,0,true,"","",12l,RuleSetType.US_OIL, 5),
                new HOSRecAdjusted("54",HOSStatus.TRAVELTIME_OCCUPANT,new Date(1275866100000l),TimeZone.getTimeZone("UTC"),new Date(1275866100000l),0l,69,0,true,"","",150l,RuleSetType.US_OIL, 5),
                new HOSRecAdjusted("generated",HOSStatus.TRAVELTIME_OCCUPANT,new Date(1275875100000l),TimeZone.getTimeZone("UTC"),new Date(1275875100000l),0l,69,0,true,"","",11l,RuleSetType.US_OIL, 5),
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1275875100000l),TimeZone.getTimeZone("UTC"),new Date(1275875100000l),15l,69,1,false,"","",3l,RuleSetType.US_OIL, 5),
                new HOSRecAdjusted("53",HOSStatus.OFF_DUTY,new Date(1275876000000l),TimeZone.getTimeZone("UTC"),new Date(1275876000000l),615l,70,16,false,"","",615l,RuleSetType.US_OIL, 5),
                
        },
        {   // test14_01242010_01312010_rule16
            new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1264316400000l),TimeZone.getTimeZone("UTC"),new Date(1264316400000l),1440l,0,96,false,"","",1440l,RuleSetType.US_7DAY, 17),
        },
    };
    public HOSRecAdjusted expectedOriginalList[][]  = {
            {     // test0_03302010_04012010_rule2
            },
            {     // test1_01242010_01312010_rule2
            },
            {     // test2_03012010_03052010_rule2
            },
            {     // test3_06202010_06302010_rule13
            },
            {     // test4_06202010_06302010_rule7
            },
            {     // test5_06202010_06302010_rule1
            },
            {     // test6_04182010_04202010_rule10
            },
            {     // test7_06202010_06302010_rule14
            },
            {     // test8_06202010_06302010_rule6
            },
            {     // test9_06202010_06302010_rule8
            },
            {     // test10_06052010_06152010_rule9
            },
            {     // test11_01192010_01212010_rule11
            },
            {     // test12_07132010_07172010_personalTime
            },
            {     // test13_06062010_06102010_travelTimeOccupant
//                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1275804000000l),TimeZone.getTimeZone("UTC"),new Date(1275804000000l),1020l,0,68,false,"","",1022l,RuleSetType.US_OIL, 1),
//                new HOSRecAdjusted("54",HOSStatus.ON_DUTY,new Date(1275865200000l),TimeZone.getTimeZone("UTC"),new Date(1275865200000l),180l,68,12,false,"","",174l,RuleSetType.US_OIL, 5),
//                new HOSRecAdjusted("53",HOSStatus.OFF_DUTY,new Date(1275876000000l),TimeZone.getTimeZone("UTC"),new Date(1275876000000l),615l,80,16,false,"","",624l,RuleSetType.US_OIL, 5),
                
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1275804000000l),TimeZone.getTimeZone("UTC"),new Date(1275804000000l),1020l,0,68,false,"","",1020l,RuleSetType.US_OIL, 1),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1275865200000l),TimeZone.getTimeZone("UTC"),new Date(1275865200000l),0l,68,0,false,"","",2l,RuleSetType.US_OIL, 1),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1275865200000l),TimeZone.getTimeZone("UTC"),new Date(1275865200000l),15l,68,1,false,"","",12l,RuleSetType.US_OIL, 5),
                new HOSRecAdjusted("54",HOSStatus.ON_DUTY,new Date(1275866100000l),TimeZone.getTimeZone("UTC"),new Date(1275866100000l),150l,69,10,false,"","",150l,RuleSetType.US_OIL, 5),
                new HOSRecAdjusted("generated",HOSStatus.ON_DUTY,new Date(1275875100000l),TimeZone.getTimeZone("UTC"),new Date(1275875100000l),15l,79,1,false,"","",11l,RuleSetType.US_OIL, 5),
                new HOSRecAdjusted("generated",HOSStatus.OFF_DUTY,new Date(1275875100000l),TimeZone.getTimeZone("UTC"),new Date(1275875100000l),0l,80,0,false,"","",3l,RuleSetType.US_OIL, 5),
                new HOSRecAdjusted("53",HOSStatus.OFF_DUTY,new Date(1275876000000l),TimeZone.getTimeZone("UTC"),new Date(1275876000000l),615l,80,16,false,"","",615l,RuleSetType.US_OIL, 5),
                
            },
            {     // test14_01242010_01312010_rule16
            },
    };
    public Boolean expectedEdited[] = {
            Boolean.FALSE,
            Boolean.FALSE,
            Boolean.FALSE,
            Boolean.FALSE,
            Boolean.FALSE,
            Boolean.FALSE,
            Boolean.FALSE,
            Boolean.FALSE,
            Boolean.FALSE,
            Boolean.FALSE,
            Boolean.FALSE,
            Boolean.FALSE,
            Boolean.FALSE,
            Boolean.TRUE,
            Boolean.FALSE,
    };
    
    ExpectedRecap expectedRecap[] = {
            //0 test0_03302010_04012010_rule2
        new ExpectedRecap(RecapType.US,RuleSetType.US_OIL,8,"08.25","00.00","-","177.25","00.00","","",0),
            // 1 test1_01242010_01312010_rule2
        new ExpectedRecap(RecapType.US,RuleSetType.US_OIL,1,"00.00","70.00","-","00.00","70.00","","",0),
            //2 test2_03012010_03052010_rule2
        new ExpectedRecap(RecapType.US,RuleSetType.US_OIL,1,"00.00","70.00","-","00.00","70.00","","",0),
            //3 test3_06202010_06302010_rule13
        null, 
            //4 test4_06202010_06302010_rule7
        new ExpectedRecap(RecapType.US,RuleSetType.TEXAS,1,"00.00","70.00","-","00.00","70.00","","",0),
            //5 test5_06202010_06302010_rule1
        new ExpectedRecap(RecapType.US,RuleSetType.US,1,"00.00","70.00","-","00.00","70.00","","",0),
            //6 test6_04182010_04202010_rule10
        null, 
            //7 test7_06202010_06302010_rule14
        null, 
            //8 test8_06202010_06302010_rule6
        new ExpectedRecap(RecapType.CANADA,RuleSetType.CANADA_HOME_OFFICE,14,"01.50","119.25","01.50","01.50","118.00","02.00","",0),
//        new ExpectedRecap(RecapType.CANADA,RuleSetType.CANADA_HOME_OFFICE,14,"01.50","120.00","00.50","00.50","119.50","00.50","",0),
            //9 test9_06202010_06302010_rule8
        null, 
            //10 test10_06052010_06152010_rule9
        new ExpectedRecap(RecapType.CANADA_2007,RuleSetType.CANADA_2007_CYCLE_1,6,"01.25","45.00","","","68.75","","26.25",1),
            //11 test11_01192010_01212010_rule11
        new ExpectedRecap(RecapType.CANADA_2007,RuleSetType.CANADA_2007_60_DEGREES_CYCLE_1,1,"00.00","80.00","","","80.00","","00.00",1),
            //12 test12_07132010_07172010_personalTime
        new ExpectedRecap(RecapType.CANADA_2007,RuleSetType.CANADA_2007_CYCLE_1,3,"11.75","48.00","","","36.25","","33.75",1),
//        new ExpectedRecap(RecapType.CANADA_2007,RuleSetType.CANADA_2007_CYCLE_1,1,"11.75","70.00","","","70.00","","00.00",1),
            //13 test13_06062010_06102010_travelTimeOccupant
        new ExpectedRecap(RecapType.US,RuleSetType.US_OIL,1,"00.00","70.00","-","00.00","70.00","","",0),
            // 14 test14_01242010_01312010_rule16
        new ExpectedRecap(RecapType.US,RuleSetType.US_7DAY,1,"00.00","60.00","00.00","-","60.00","","",0),
    };
    
    @Test
    public void gainTestCases() {
// testcase 7 slight rounding issue on 6/21 9:45
            for (int testCaseCnt = 0; testCaseCnt < testCaseName.length; testCaseCnt++) {
//int testCaseCnt = 14; {
//System.out.println("TestCase: " + testCaseCnt);            
            DDLDataSet ddlTestData = new DDLDataSet(testCaseName[testCaseCnt]);
//for (HOSRecord record : ddlTestData.hosRecordList)   
//    record.dump2();
            HosDailyDriverLogReportCriteria hosDailyDriverLogReportCriteria = new HosDailyDriverLogReportCriteria(Locale.US, Boolean.FALSE);
//System.out.println("interval: " + ddlTestData.interval);            
            hosDailyDriverLogReportCriteria.initCriteriaList(ddlTestData.interval, ddlTestData.hosRecordList, ddlTestData.hosVehicleDayDataList,
                ddlTestData.hosOccupantLogList, ddlTestData.driver, ddlTestData.account, ddlTestData.group);
            
            // check the data
            List<ReportCriteria> criteriaList = hosDailyDriverLogReportCriteria.getCriteriaList();
            assertEquals("expected one ReportCriteria item for each day", ddlTestData.numDays, criteriaList.size());
            
            int dayIdx = testDay[testCaseCnt];
            HosDailyDriverLog hosDailyDriverLog = (HosDailyDriverLog)criteriaList.get(dayIdx).getMainDataset().get(0);

            dump("DDL", testCaseCnt, hosDailyDriverLogReportCriteria.getCriteriaList(), FormatType.PDF);
            dump("DDL", testCaseCnt, hosDailyDriverLogReportCriteria.getCriteriaList(), FormatType.HTML);
            
            List<HOSRecAdjusted> correctedList =  hosDailyDriverLog.getCorrectedGraphList();
//for (HOSRecAdjusted adjustedRec : correctedList) {
//    adjustedRec.dump();
//}
//System.out.println("---");
            assertEquals("corrected list size ", expectedAdjustedList[testCaseCnt].length, correctedList.size());
            int recCnt = 0;
            for (HOSRecAdjusted adjustedRec : correctedList) {
//adjustedRec.dump2();                
                compareHOSRecAdjusted(expectedAdjustedList[testCaseCnt][recCnt], adjustedRec, recCnt, testCaseCnt);
                recCnt++;
            }
            assertEquals("day edited testcase " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedEdited[testCaseCnt], hosDailyDriverLog.getEdited());
//System.out.println("------------------");            
            List<HOSRecAdjusted> originalList = hosDailyDriverLog.getOriginalGraphList();
            if (hosDailyDriverLog.getEdited()) {
                recCnt = 0;
                for (HOSRecAdjusted originalRec : originalList) {
                    compareHOSRecAdjusted(expectedOriginalList[testCaseCnt][recCnt], originalRec, recCnt, testCaseCnt);
//originalRec.dump();
                    recCnt++;
                }
            }
            else {
                assertNull("original list should be null for " + testCaseCnt + " " +testCaseName[testCaseCnt], originalList);
            }
            
            
            List<Recap> recapList = hosDailyDriverLog.getRecap();
            if (recapList == null) {
                assertEquals("expected null recap for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt], null);
            }
            else {
                Recap baseRecap = recapList.get(0);
                assertEquals("expected recap type for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].recapType, baseRecap.getRecapType());
                assertEquals("expected ruleset recap type for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].ruleSetType, baseRecap.getRuleSetType());
                if (baseRecap.getRecapType() == RecapType.US) {
                    RecapUS recap = (RecapUS)baseRecap;
                    assertEquals("expected recap day for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].day, recap.getDay());
                    assertEquals("expected recap hours worked for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].hoursWorkedToday, recap.getHoursWorkedToday());
                    assertEquals("expected recap hours avail for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].hoursAvailToday, recap.getHoursAvailToday());
                    assertEquals("expected recap hours worked 7 days for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].hoursWorked7Days, recap.getHoursWorked7Days());
                    assertEquals("expected recap hours worked 8 days for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].hoursWorked8Days, recap.getHoursWorked8Days());
                    assertEquals("expected recap hours avail tomorrow for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].hoursAvailTomorrow, recap.getHoursAvailTomorrow());
                }
                else if (baseRecap.getRecapType() == RecapType.CANADA) {
                    RecapCanada recap = (RecapCanada)baseRecap;
                    assertEquals("expected recap hours worked for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].hoursWorkedToday, recap.getHoursWorkedToday());
                    assertEquals("expected recap hours avail for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].hoursAvailToday, recap.getHoursAvailToday());
                    assertEquals("expected recap hours worked 7 days for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].hoursWorked7Days, recap.getHoursWorked7Days());
                    assertEquals("expected recap hours worked 8 days for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].hoursWorked8Days, recap.getHoursWorked8Days());
                    assertEquals("expected recap hours worked 14 days for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].hoursWorked14Days, recap.getHoursWorked14Days());
                    assertEquals("expected recap hours avail tomorrow for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].hoursAvailTomorrow, recap.getHoursAvailTomorrow());
                }
                else if (baseRecap.getRecapType() == RecapType.CANADA_2007) {
                    RecapCanada2007 recap = (RecapCanada2007)baseRecap;
                    assertEquals("expected recap day for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].day, recap.getDay());
                    assertEquals("expected recap hours worked for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].hoursWorkedToday, recap.getHoursWorkedToday());
                    assertEquals("expected recap hours avail for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].hoursAvailToday, recap.getHoursAvailToday());
                    assertEquals("expected recap hours avail tomorrow for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].hoursAvailTomorrow, recap.getHoursAvailTomorrow());
                    assertEquals("expected recap hours worked cycle for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].hoursWorkedCycle, recap.getHoursWorkedCycle());
                    assertEquals("expected recap hours worked cycle for " + testCaseCnt + " " +testCaseName[testCaseCnt], expectedRecap[testCaseCnt].cycle, recap.getCycle());
                    
                }
            }
  
        }
    }
    
    HOSRecord[] hosRecords = {
//            public HOSRecord(Long hosLogID, Integer driverID,
//                    RuleSetType driverDotType, Integer vehicleID, String vehicleName, Boolean vehicleIsDOT,
//                    Long vehicleOdometer, Date logTime, Date addedTime, TimeZone timeZone, HOSStatus status, HOSOrigin origin, String location, Float lat, Float lng, Long distance,
//                    String trailerID, String serviceID, Boolean singleDriver, Boolean edited, String editUserName, Boolean deleted) {
            new HOSRecord(1l, 1, RuleSetType.US, null, null, false, 
                    0l, new Date(), new Date(), TimeZone.getDefault(), HOSStatus.DRIVING,
                    HOSOrigin.KIOSK, "slc", 0.0f, 0.0f, 0l, null, null, true, true, "", false, 0f,0f),
             new HOSRecord(1l, 1, RuleSetType.US, null, null, false, 
                            0l, new Date(), new Date(), TimeZone.getDefault(), HOSStatus.ON_DUTY,
                            HOSOrigin.PORTAL, "slc", 0.0f, 0.0f, 0l, null, null, true, true, "", false, 0f, 0f),
             new HOSRecord(1l, 1, RuleSetType.US, null, null, false, 
                                    0l, new Date(), new Date(), TimeZone.getDefault(), HOSStatus.ON_DUTY,
                                    HOSOrigin.DEVICE, "slc", 0.0f, 0.0f, 0l, null, null, true, false, "", false, 0f, 0f),
    };

    RemarkLog[] expectedRemarkLogs = {
//            public RemarkLog(HOSStatus status, Date logTimeDate, TimeZone logTimeZone, Boolean edited, String location, String originalLocation, Boolean deleted, Number startOdometer,
//                    String statusDescription, Boolean locationEdited, String editor) {
            new RemarkLog(HOSStatus.DRIVING, new Date(), TimeZone.getDefault(), true, "slc", "slc", false, 0l, "Driving", false, "Driver Kiosk"), 
            new RemarkLog(HOSStatus.ON_DUTY, new Date(), TimeZone.getDefault(), true, "slc", "slc", false, 0l, "On Duty - Not Driving", false, ""), 
            new RemarkLog(HOSStatus.ON_DUTY, new Date(), TimeZone.getDefault(), true, "slc", "slc", false, 0l, "On Duty - Not Driving", false, ""), 
            
    };
    
    @Test
    public void remarks() {
        HosDailyDriverLogReportCriteria ddlCriteria = new HosDailyDriverLogReportCriteria(Locale.US, Boolean.FALSE);
        assertNotNull("resource bundle should be initialized", ddlCriteria.getResourceBundle());
        int cnt = 0;
        for (HOSRecord hosRecord : hosRecords) {
            hosRecord.setOriginalLocation(hosRecord.getLocation());
            RemarkLog remarkLog = ddlCriteria.populateRemarkLog(hosRecord);
            compareRemarkLog(cnt, expectedRemarkLogs[cnt], remarkLog);
            cnt++;
        }
        cnt = 0;
        for (HOSRecord hosRecord : hosRecords) {
            String editedLocation = hosRecord.getLocation() + "xx"; 
            hosRecord.setLocation(editedLocation);
            hosRecord.setEdited(true);
            expectedRemarkLogs[cnt].setLocation(editedLocation);
            expectedRemarkLogs[cnt].setLocationEdited(true);
            RemarkLog remarkLog = ddlCriteria.populateRemarkLog(hosRecord);
            compareRemarkLog(cnt, expectedRemarkLogs[cnt], remarkLog);
            cnt++;
        }
    }

    private void compareRemarkLog(int cnt, RemarkLog expectedRemarkLog, RemarkLog remarkLog) {
        assertEquals(cnt + " isDeleted", expectedRemarkLog.getDeleted(), remarkLog.getDeleted());
        assertEquals(cnt + " Editor", expectedRemarkLog.getEditor(), remarkLog.getEditor());
        assertEquals(cnt + " Location", expectedRemarkLog.getLocation(), remarkLog.getLocation());
        assertEquals(cnt + " LocationEdited", expectedRemarkLog.getLocationEdited(), remarkLog.getLocationEdited());
        assertEquals(cnt + " OriginalLocation", expectedRemarkLog.getOriginalLocation(), remarkLog.getOriginalLocation());
        assertEquals(cnt + " Status", expectedRemarkLog.getStatus(), remarkLog.getStatus());
    }

    private void compareHOSRecAdjusted(HOSRecAdjusted expectedRec, HOSRecAdjusted rec, int recCnt, int testCaseCnt) {
        String prefix = "testcase: " + testCaseCnt + " " + testCaseName[testCaseCnt] + " adjustedRec [" +recCnt + "] field: "; 
        assertEquals(prefix+"ID ", expectedRec.getId(), rec.getId()); 
        assertEquals(prefix+"Status ", expectedRec.getStatus(), rec.getStatus()); 
        assertEquals(prefix+"LogTimeDate ", expectedRec.getLogTimeDate(), rec.getLogTimeDate()); 
        assertEquals(prefix+"LogTimeZone ", expectedRec.getLogTimeZone(),  rec.getLogTimeZone());
        assertEquals(prefix+"AdjustedTime ", expectedRec.getAdjustedTime(), rec.getAdjustedTime()); 
        assertEquals(prefix+"TotalAdjustedMinutes ", expectedRec.getTotalAdjustedMinutes(), rec.getTotalAdjustedMinutes()); 
        assertEquals(prefix+"StartIncrement ", expectedRec.getStartIncrement(), rec.getStartIncrement()); 
        assertEquals(prefix+"TotalIncrements ", expectedRec.getTotalIncrements(), rec.getTotalIncrements()); 
        assertEquals(prefix+"Edited ", expectedRec.isEdited(), rec.isEdited()); 
        assertEquals(prefix+"ServiceID ", expectedRec.getServiceID(), rec.getServiceID()); 
        assertEquals(prefix+"TrailerID ", expectedRec.getTrailerID(), rec.getTrailerID()); 
        assertEquals(prefix+"TotalRealMinutes ", expectedRec.getTotalRealMinutes(), rec.getTotalRealMinutes()); 
        assertEquals(prefix+"RuleType ", expectedRec.getRuleType(), rec.getRuleType()); 
    }





    class ExpectedRecap {
        
        // all
        RecapType recapType;
        RuleSetType ruleSetType;
        Integer day;
        String hoursWorkedToday;
        
        // US, CANADA
        String hoursAvailToday;
        String hoursWorked7Days;
        String hoursWorked8Days;
        String hoursAvailTomorrow;

        // CANADA
        String hoursWorked14Days;
        
        // CANADA2007
        String hoursWorkedCycle;
        int cycle;

        public ExpectedRecap(RecapType recapType,RuleSetType ruleSetType,
                Integer day, String hoursWorkedToday, String hoursAvailToday, String hoursWorked7Days, String hoursWorked8Days, String hoursAvailTomorrow,
                String hoursWorked14Days, String hoursWorkedCycle, int cycle) {
            this.recapType = recapType;
            this.ruleSetType = ruleSetType;
            this.day = day;
            this.hoursWorkedToday = hoursWorkedToday;
            this.hoursAvailToday = hoursAvailToday;
            this.hoursWorked7Days = hoursWorked7Days;
            this.hoursWorked8Days = hoursWorked8Days;
            this.hoursAvailTomorrow = hoursAvailTomorrow;
            this.hoursWorked14Days = hoursWorked14Days;
            this.hoursWorkedCycle = hoursWorkedCycle;
            this.cycle = cycle;
        }

        public void dump() {
            
            if (recapType == RecapType.US) {
                System.out.println("        new ExpectedRecap(RecapType.US," + 
                        "RuleSetType."+ruleSetType.getName()+"," +
                        day + "," +
                        "\"" + hoursWorkedToday + "\"," +
                        "\"" + hoursAvailToday + "\"," +
                        "\"" + hoursWorked7Days + "\"," +
                        "\"" + hoursWorked8Days + "\"," +
                        "\"" + hoursAvailTomorrow + "\"," +
                        "\"\"," +
                        "\"\"," +
                        "0),");
            }
            else if (recapType ==  RecapType.CANADA) {
              System.out.println("        new ExpectedRecap(RecapType.CANADA," + 
                      "RuleSetType."+ruleSetType.getName()+"," +
                      day + "," +
                      "\"" + hoursWorkedToday + "\"," +
                      "\"" + hoursAvailToday + "\"," +
                      "\"" + hoursWorked7Days + "\"," +
                      "\"" + hoursWorked8Days + "\"," +
                      "\"" + hoursAvailTomorrow + "\"," +
                      "\"" + hoursWorked14Days + "\"," +
                      "\"\"," +
                      "0),");
            }
            else if (recapType == RecapType.CANADA_2007) {
              System.out.println("        new ExpectedRecap(RecapType.CANADA_2007," + 
                      "RuleSetType."+ruleSetType.getName()+"," +
                      day + "," +
                      "\"" + hoursWorkedToday + "\"," +
                      "\"" + hoursAvailToday + "\"," +
                      "\"\"," +
                      "\"\"," +
                      "\"" + hoursAvailTomorrow + "\"," +
                      "\"\"," +
                      "\"" + hoursWorkedCycle + "\"," +
                      cycle+"),");
            }
            
        }
    }
}
