package com.inthinc.pro.automation.deviceEnums;

import java.util.EnumSet;
import java.util.HashMap;

public enum TiwiWmpMsp implements DeviceTypesUnique {

    /* WMP MSP Attributes */

    WMPMSP_ATTR_GPIO_NUM(0),
    WMPMSP_ATTR_GPIO_LEVEL(1),
    WMPMSP_ATTR_GPIO_17_24(2),
    WMPMSP_ATTR_DMM_STATUS_STRUCTURE_REV(4),
    WMPMSP_ATTR_DMM_CONFIGURATION_REV(5),
    WMPMSP_ATTR_DMM_ORIENTATION_CABLE_DIR(6),
    WMPMSP_ATTR_DMM_CAL_STATUS(7),
    WMPMSP_ATTR_DMM_CONFIGURATION_REV_TEMP_COMP(8),
    WMPMSP_ATTR_TEMPCOMP_ENABLED(9),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_COLLECTION_ENABLED(10),
    WMPMSP_ATTR_TEMPCOMP_SLOPES_IN_BUFFER(11),
    WMPMSP_ATTR_POWERSTATE(12),
    WMPMSP_ATTR_ORIENT_STATUS(13),
    WMPMSP_ATTR_AGCTL_STATUS(14),
    WMPMSP_ATTR_CRASH_DATA(15),
    WMPMSP_ATTR_PACKET_NUMBER(16),
    WMPMSP_ATTR_MOVEMENT(17),
    WMPMSP_ATTR_RFID_PWRSTATE(18),
    WMPMSP_ATTR_TEMPSAMPLE_RESULT(19),
    WMPMSP_ATTR_RAW_DATA_TYPE(20),
    WMPMSP_ATTR_USED_CONFIGBKUP_CNT(21),
    WMPMSP_ATTR_USED_TEMPCOMP_BKUP_CNT(22),
    WMPMSP_ATTR_BKUP_CONFIG_OP(23),
    WMPMSP_ATTR_MVMT_TIMEOUT(24),

    /* Values From 8192 To 16383 Are Two Byte Values */
    WMPMSP_ATTR_DMM_FIRMWARE_REV(8192),
    WMPMSP_ATTR_DMM_FIRMWARE_REV_PREVIOUS(8193),
    WMPMSP_ATTR_DMM_ORIENTATION_A11(8194),
    WMPMSP_ATTR_DMM_ORIENTATION_A12(8195),
    WMPMSP_ATTR_DMM_ORIENTATION_A13(8196),
    WMPMSP_ATTR_DMM_CAL_OFFSET_UAXIS(8197),
    WMPMSP_ATTR_DMM_CAL_OFFSET_VAXIS(8198),
    WMPMSP_ATTR_DMM_CAL_OFFSET_WAXIS(8199),
    WMPMSP_ATTR_DMM_CAL_OFFSET_TEMPSENSOR(8200),
    WMPMSP_ATTR_DMM_CRASH_G_LEVEL(8201),
    WMPMSP_ATTR_DMM_CRASH_DELTAV_X(8202),
    WMPMSP_ATTR_DMM_CRASH_DELTAV_Y(8203),
    WMPMSP_ATTR_DMM_CRASH_DELTAV_Z(8204),
    WMPMSP_ATTR_DMM_HARDACCEL_LEVEL(8205),
    WMPMSP_ATTR_DMM_HARDACCEL_AVERAGECHANGE(8206),
    WMPMSP_ATTR_DMM_HARDACCEL_WINDOW(8207),
    WMPMSP_ATTR_DMM_HARDACCEL_DELTAV(8208),
    WMPMSP_ATTR_DMM_HARDBRAKE_LEVEL(8209),
    WMPMSP_ATTR_DMM_HARDBRAKE_AVERAGECHANGE(8210),
    WMPMSP_ATTR_DMM_HARDBRAKE_WINDOW(8211),
    WMPMSP_ATTR_DMM_HARDBRAKE_DELTAV(8212),
    WMPMSP_ATTR_DMM_HARDTURN_LEVEL(8213),
    WMPMSP_ATTR_DMM_HARDTURN_AVERAGECHANGE(8214),
    WMPMSP_ATTR_DMM_HARDTURN_WINDOW(8215),
    WMPMSP_ATTR_DMM_HARDTURN_DELTAV(8216),
    WMPMSP_ATTR_DMM_HARDVERTICAL_LEVEL(8217),
    WMPMSP_ATTR_DMM_HARDVERTICAL_AVERAGECHANGE(8218),
    WMPMSP_ATTR_DMM_HARDVERTICAL_WINDOW(8219),
    WMPMSP_ATTR_DMM_HARDVERTICAL_DELTAV(8220),
    WMPMSP_ATTR_XRAW(8221),
    WMPMSP_ATTR_YRAW(8222),
    WMPMSP_ATTR_ZRAW(8223),
    WMPMSP_ATTR_TEMP(8224),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_U(8225),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_V(8226),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_W(8227),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_U1(8228),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_U2(8229),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_U3(8230),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_U4(8231),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_U5(8232),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_U6(8233),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_U7(8234),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_U8(8235),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_U9(8236),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_V1(8237),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_V2(8238),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_V3(8239),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_V4(8240),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_V5(8241),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_V6(8242),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_V7(8243),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_V8(8244),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_V9(8245),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_W1(8246),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_W2(8247),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_W3(8248),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_W4(8249),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_W5(8250),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_W6(8251),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_W7(8252),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_W8(8253),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_DATA_W9(8254),
    WMPMSP_ATTR_TEMPCOMP_SAMPLE_MAX_U(8255),
    WMPMSP_ATTR_TEMPCOMP_SAMPLE_MAX_V(8256),
    WMPMSP_ATTR_TEMPCOMP_SAMPLE_MAX_W(8257),
    WMPMSP_ATTR_TEMPCOMP_SAMPLE_MIN_U(8258),
    WMPMSP_ATTR_TEMPCOMP_SAMPLE_MIN_V(8259),
    WMPMSP_ATTR_TEMPCOMP_SAMPLE_MIN_W(8260),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_ESTIMATES(8261),
    WMPMSP_ATTR_TEMPCOMP_SLOPE_UPDATES(8262),
    WMPMSP_ATTR_DMM_ORIENTATION_A21(8263),
    WMPMSP_ATTR_DMM_ORIENTATION_A22(8264),
    WMPMSP_ATTR_DMM_ORIENTATION_A23(8265),
    WMPMSP_ATTR_DMM_ORIENTATION_A31(8266),
    WMPMSP_ATTR_DMM_ORIENTATION_A32(8267),
    WMPMSP_ATTR_DMM_ORIENTATION_A33(8268),
    WMPMSP_ATTR_DMM_EVENT_DELTAV_X(8269),
    WMPMSP_ATTR_DMM_EVENT_DELTAV_Y(8270),
    WMPMSP_ATTR_DMM_EVENT_DELTAV_Z(8271),
    WMPMSP_ATTR_CRASH_ADC_COUNT_X(8272),
    WMPMSP_ATTR_CRASH_ADC_COUNT_Y(8273),
    WMPMSP_ATTR_CRASH_ADC_COUNT_Z(8274),
    WMPMSP_ATTR_VEH_VOLT(8275),
    WMPMSP_ATTR_AGCTL_MSG(8276),
    WMPMSP_ATTR_AGCTL_STATUS_(8277),
    WMPMPS_ATTR_TEMP_CONFIG_BKUP_WRITTEN(8279),

    /* Values From 16384 To 24575 Are 4 Byte Values */
    WMPMSP_ATTR_DMM_EVENTDATA(16384),
    WMPMSP_ATTR_AGCTL_MSG_(16385),
    WMPMSP_ATTR_RFID_LOW(16386),
    WMPMSP_ATTR_RFID_HIGH(16387),
    WMPMSP_ATTR_XSQUARE(16388),
    WMPMSP_ATTR_YSQUARE(16389),
    WMPMSP_ATTR_ZSQUARE(16390);

    private int code;

    private TiwiWmpMsp(int c) {
        code = c;
    }

    public Integer getValue() {
        return code;
    }

    private static HashMap<Integer, TiwiWmpMsp> lookupByCode = new HashMap<Integer, TiwiWmpMsp>();

    static {
        for (TiwiWmpMsp p : EnumSet.allOf(TiwiWmpMsp.class)) {
            lookupByCode.put(p.getValue(), p);
        }
    }

    public TiwiWmpMsp valueOf(Integer code) {
        return lookupByCode.get(code);
    }
}
