package com.inthinc.pro.automation.enums;

import java.util.EnumSet;
import java.util.HashMap;

public enum TiwiAttrs implements DeviceTypesUnique {

    ATTR_TYPE_TOP_SPEED(1),
    ATTR_TYPE_AVG_SPEED(2),
    ATTR_TYPE_SPEED_LIMIT(3),
    ATTR_TYPE_AVG_RPM(4),
    ATTR_TYPE_RESET_REASON(5),
    ATTR_TYPE_MANUAL_RESET_REASON(6),
    ATTR_TYPE_FWDCMD_STATUS(7),
    ATTR_TYPE_VIOLATION_FLAGS(8),
    ATTR_TYPE_ENG_TEMP(9),
    ATTR_TYPE_FUEL_LEVEL(10),
    ATTR_TYPE_THROTTLE(11),
    ATTR_TYPE_GPS_SATS_SNR_COUNT(12),
    ATTR_TYPE_GPS_SATS_SNR_MIN(13),
    ATTR_TYPE_GPS_SATS_SNR_MAX(14),
    ATTR_TYPE_DMM_MONITOR_X30(15),
    ATTR_TYPE_DMM_MONITOR_X50(16),
    ATTR_TYPE_DMM_MONITOR_X67(17),
    ATTR_TYPE_DMM_MONITOR_Y30(18),
    ATTR_TYPE_DMM_MONITOR_Y50(19),
    ATTR_TYPE_DMM_MONITOR_Y67(20),
    ATTR_TYPE_GPS_SATS_SNR_MEDIAN(21),
    ATTR_TYPE_GPS_SATS_PDOP_10X(22),
    ATTR_TYPE_GPS_SATS_HDOP_10X(23),
    ATTR_TYPE_SEVERITY(24),
    ATTR_TYPE_DMM_VERSION(25),
    ATTR_TYPE_DMM_ORIENTATION(26),
    ATTR_TYPE_DMM_DVX(27),
    ATTR_TYPE_DMM_YLEVEL(28),
    ATTR_TYPE_DMM_ZLEVEL(29),
    ATTR_TYPE_SMTLS_ENABLED(30),
    ATTR_TYPE_SMTLS_SECURITY_DISABLED(31),
    ATTR_TYPE_SMTLS_DEACTIVATE_OVERRIDE(32),
    ATTR_TYPE_SMTLS_EMU_DOWNLOADED(33),
    ATTR_TYPE_SMTLS_EMU_NAME_VERIFICATION_OVERRIDE(34),
    ATTR_TYPE_SMTLS_BUILD_NUM(35),
    ATTR_TYPE_SMTLS_PERCENT_SUCCESSFUL_REQUEST_RESPONSE_COMMS(36),
    ATTR_TYPE_OBD_SEATBELT_STATUS(37),
    ATTR_TYPE_OBD_SEATBELT_AVAIL(38),
    ATTR_TYPE_SPEED_IN_EXCEPTION_MAP(39),
    ATTR_TYPE_GPS_MOST_LIKELY_LOCKED(40),
    ATTR_TYPE_GGA_GPS_QUALITY(41),
    ATTR_TYPE_GPS_SPEED(42),
    ATTR_TYPE_OBD_RPM_AVAIL(43),
    ATTR_TYPE_OBD_SPEED_AVAIL(44),
    ATTR_TYPE_OBD_VIN_DIGIT_1(45),
    ATTR_TYPE_DMM_CAL_STATUS(46),
    ATTR_TYPE_ATTR_CURRENT_IGN(47),
    ATTR_TYPE_NUMBER_OF_GPS_REBOOTS(48),
    ATTR_TYPE_PERCENTAGE_OF_TIME_SPEED_FROM_OBD_USED(49),
    ATTR_TYPE_PERCENTAGE_OF_TIME_SPEED_FROM_GPS_USED(50),
    ATTR_TYPE_STATS(51),
    ATTR_TYPE_AGPS_ERROR_CODE(52),
    ATTR_TYPE_UNPLUGGED_WHILE_ASLEEP(53),
    ATTR_LOGOUT_TYPE(54),
    ATTR_SAT_EPH_CNT(55),
    ATTR_WITNESS_EVENT_TYPE(56),
    ATTR_GPINPUT_STATE(57),
    ATTR_SEATBELT_SRC(58),
    ATTR_VBCPU_BOOTMODE(59),
    ATTR_DWNLD_TYPE(60),
    ATTR_NUM_CONFIG_DUMPS(61),
    ATTR_NUM_REQSET(62),
    ATTR_BASE_VER(63),
    ATTR_TYPE_DISTANCE(129),
    ATTR_TYPE_MAX_RPM(130),
    ATTR_TYPE_DELTA_VX(131),
    ATTR_TYPE_DELTA_VY(132),
    ATTR_TYPE_DELTA_VZ(133),
    ATTR_TYPE_VEHICLE_BATTERY(134),
    ATTR_TYPE_BACKUP_BATTERY(135),
    ATTR_TYPE_GPS_SATS_SNR_MEAN_100X(136),
    ATTR_TYPE_GPS_SATS_SNR_STDDEV_100X(137),
    ATTR_TYPE_GPS_LOCK_TIME(138),
    ATTR_TYPE_SMTLS_FIRMWARE_REV(139),
    ATTR_TYPE_COURSE(140),
    ATTR_TYPE_OBD_RPM(141),
    ATTR_TYPE_OBD_SPEED(142),
    ATTR_TYPE_SMTLS_LOGGED_TX_COUNT(143),
    ATTR_TYPE_SMTLS_OP_MODE(144),
    ATTR_TYPE_ODOMETER_BY_COORDINATES(145),
    ATTR_TYPE_A_AND_D_SPACE(146),
    ATTR_TYPE_APPLICATION_SPACE(147),
    ATTR_TYPE_BOUNDARY_ID(148),
    ATTR_TYPE_MPG(149),
    ATTR_TYPE_LOW_POWER_MODE_TIMEOUT(150),
    ATTR_TYPE_NUMBER_OF_TIMES_A_SPEEDING_VIOLATION_WAS_EITHER_PREVENTED_OR_SQUELCHED_(165),
    ATTR_TYPE_PERCENTAGE_OF_POINTS_THAT_PASSED_THE_FILTER_(166),
    ATTR_TYPE_ZONE_ID(192),
    ATTR_TYPE_FIRMWARE_VERSION(193),
    ATTR_TYPE_FWDCMD_ID(194),
    ATTR_TYPE_FWDCMD_COMMAND(195),
    ATTR_TYPE_FWDCMD_ERROR(196),
    ATTR_TYPE_SMTLS_TX_ATTEMPTS(197),
    ATTR_TYPE_LAT_VERB(198),
    ATTR_TYPE_LONG_VERB(199),
    ATTR_TYPE_STREET_ID(200),
    ATTR_TYPE_SPEED_ID(201),
    ATTR_TYPE_EMU_HASH_1(202),
    ATTR_TYPE_EMU_HASH_2(203),
    ATTR_TYPE_EMU_HASH_3(204),
    ATTR_TYPE_EMU_HASH_4(205),
    ATTR_TYPE_OBD_X1_TO_X4(206),
    ATTR_TYPE_OBD_X5_TO_X8(207),
    ATTR_TYPE_OBD_X9_TO_X12(208),
    ATTR_TYPE_OBD_X13_TO_X16(209),
    ATTR_TYPE_OBD_X17_TO_X20(210),
    ATTR_TYPE_OBD_X21_TO_X24(211),
    ATTR_TYPE_OBD_X25_TO_X28(212),
    ATTR_TYPE_SMTLS_LOGGED_RX_COUNT(213),
    ATTR_TYPE_OBD_VIN_DIGIT_2_TO_5(214),
    ATTR_TYPE_OBD_VIN_DIGIT_6_TO_9(215),
    ATTR_TYPE_OBD_VIN_DIGIT_10_TO_13(216),
    ATTR_TYPE_OBD_VIN_DIGIT_14_TO_17(217),
    ATTR_TYPE_LOW_IDLE(219),
    ATTR_TYPE_HIGH_IDLE(220),
    ATTR_TYPE_RFID0(222),
    ATTR_TYPE_RFID1(223),
    ATTR_TYPE_MPG_DISTANCE(224),
    ATTR_TYPE_TRIP_DURATION(225),
    ATTR_TYPE_STRING(255),
    ATTR_BAD_ERROR(226), // Errors that we want the portal to track

    ATTR_DRIVER_ID(227),
    ATTR_TOTAL_AGPS_BYTES(228),
    ATTR_MAP_HASH(229),
    ATTR_TOTAL_BYTES_DUMPSET(230),
    ATTR_SBS_LINK_ID(231),
    ATTR_CLOSEST_SBS_LINK_ID(232),
    STATIC,

    ;

    private int code;

    private TiwiAttrs() {}

    private TiwiAttrs(int c) {
        code = c;
    }

    public Integer getValue() {
        return code;
    }

    private static HashMap<Integer, TiwiAttrs> lookupByCode = new HashMap<Integer, TiwiAttrs>();

    static {
        for (TiwiAttrs p : EnumSet.allOf(TiwiAttrs.class)) {
            lookupByCode.put(p.getValue(), p);
        }
    }

    public TiwiAttrs valueOf(Integer code) {
        return lookupByCode.get(code);
    }

}
