#!/bin/bash
U_GID="1090"
MY_GROUP_USER="tiwipro"
TOMCAT_USER="tomcat6"
MY_USER_HOME="/usr/share/tomcat6"
TOMCAT_WEBAPPS_DIR="/var/lib/tomcat6/webapps"
WARS="hoskiosk tiwiproutil tiwipro scheduler service"
GROUP_EXISTS=$(id -g ${MY_GROUP_USER} 2>/dev/null)
if [ "$?" -eq 0 ]
then
    echo "Group ${MY_GROUP_USER} already exists"
    U_GID=${GROUP_EXISTS}
else
    echo "Group ${MY_GROUP_USER} does not exist, creating"
    groupadd -g ${U_GID} ${MY_GROUP_USER}
fi


MY_USER_EXISTS=$(id -u ${TOMCAT_USER} 2>/dev/null)
if [ "$?" -eq 0 ]
then
    echo "User ${TOMCAT_USER} exists"
else
    echo "Creating user ${TOMCAT_USER}"
    useradd -M -d ${MY_USER_HOME} -s /bin/bash -g ${U_GID} ${TOMCAT_USER}
fi

echo "Adding ${TOMCAT_USER} to group ${MY_GROUP_USER}"
usermod -a -G ${MY_GROUP_USER} ${TOMCAT_USER}
if [ -d "${MY_USER_HOME}" ]
then
    chown -R ${TOMCAT_USER}:${MY_GROUP_USER} ${MY_USER_HOME}
    chmod -R u+rw,g+r,o-rwx ${MY_USER_HOME}
    find ${MY_USER_HOME} -type d -exec chmod u+rwx,g+rx,o-rwx {} \;
fi

service ${TOMCAT_USER} status 2&>1 >/dev/null
if [ "$?" -ne 1 ] && [ -d "${TOMCAT_WEBAPPS_DIR}" ]
then
    echo -n "Stopping service ${TOMCAT_USER} :"
    service ${TOMCAT_USER} stop
    while service ${TOMCAT_USER} status 2&>1 > /dev/null; do echo -n "."; sleep 1; done

    for WAR in ${WARS}
    do
        if [ -d "${TOMCAT_WEBAPPS_DIR}/${WAR}" ] && [ -f "${TOMCAT_WEBAPPS_DIR}/${WAR}.war" ]
        then
            /bin/rm -Rf ${TOMCAT_WEBAPPS_DIR}/${WAR}
        fi
        if [ -f "${TOMCAT_WEBAPPS_DIR}/${WAR}.war" ]
        then
            chown ${TOMCAT_USER}:${MY_GROUP_USER} ${TOMCAT_WEBAPPS_DIR}/${WAR}.war
            chmod u+rw,g+r,o-rwx ${TOMCAT_USER}:${MY_GROUP_USER} ${TOMCAT_WEBAPPS_DIR}/${WAR}.war
        fi
    done
service ${TOMCAT_USER} start
else
    echo "${TOMCAT_USER} doesn't seem to be installed as a service, you will need to manually start it"
fi

if [ -x "${MY_USER_HOME}/bin/setup.sh" ]
then
    echo "Running setup.sh script for ${TOMCAT_USER} at $(date)"
    ${MY_USER_HOME}/bin/setup.sh
else
    echo "No setup.sh script for tomcat ${TOMCAT_USER}"
fi
